from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
import io
from datetime import datetime

PRIMARY = colors.HexColor('#00d4aa')
DARK = colors.HexColor('#0a0a0a')
GRAY = colors.HexColor('#888888')
RED = colors.HexColor('#ff4444')
YELLOW = colors.HexColor('#f0a500')
WHITE = colors.white
LIGHT_GRAY = colors.HexColor('#f5f5f5')
DARK_GRAY = colors.HexColor('#333333')

def generate_backtest_report(backtest_data: dict, ticker: str) -> bytes:
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        'Title', parent=styles['Title'],
        fontSize=24, textColor=PRIMARY,
        spaceAfter=4, alignment=TA_LEFT,
        fontName='Helvetica-Bold'
    )
    subtitle_style = ParagraphStyle(
        'Subtitle', parent=styles['Normal'],
        fontSize=11, textColor=GRAY,
        spaceAfter=20, alignment=TA_LEFT
    )
    section_style = ParagraphStyle(
        'Section', parent=styles['Normal'],
        fontSize=13, textColor=DARK_GRAY,
        spaceBefore=16, spaceAfter=8,
        fontName='Helvetica-Bold'
    )
    normal_style = ParagraphStyle(
        'Body', parent=styles['Normal'],
        fontSize=10, textColor=DARK_GRAY,
        spaceAfter=6
    )
    small_style = ParagraphStyle(
        'Small', parent=styles['Normal'],
        fontSize=8, textColor=GRAY,
        spaceAfter=4
    )

    story = []

    story.append(Paragraph("TradeForge", title_style))
    story.append(Paragraph("AI-Powered Trading Strategy Backtest Report", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=2, color=PRIMARY, spaceAfter=16))

    info_data = [
        ['Ticker', ticker, 'Report Date', datetime.now().strftime('%B %d, %Y')],
        ['Initial Capital', f"₹{backtest_data.get('initial_capital', 0):,.0f}",
         'Final Value', f"₹{backtest_data.get('final_value', 0):,.2f}"],
        ['Data Period', 'Last 3 years', 'Generated By', 'TradeForge AI Engine'],
    ]

    info_table = Table(info_data, colWidths=[100, 150, 100, 150])
    info_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), LIGHT_GRAY),
        ('TEXTCOLOR', (0,0), (0,-1), GRAY),
        ('TEXTCOLOR', (2,0), (2,-1), GRAY),
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('FONTNAME', (1,0), (1,-1), 'Helvetica-Bold'),
        ('FONTNAME', (3,0), (3,-1), 'Helvetica-Bold'),
        ('PADDING', (0,0), (-1,-1), 8),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#dddddd')),
        ('ROWBACKGROUNDS', (0,0), (-1,-1), [WHITE, LIGHT_GRAY]),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 20))

    story.append(Paragraph("Performance Summary", section_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#eeeeee'), spaceAfter=10))

    total_return = backtest_data.get('total_return', 0)
    buy_hold = backtest_data.get('buy_hold_return', 0)
    outperformance = round(total_return - buy_hold, 2)

    metrics_data = [
        ['Metric', 'Value', 'Assessment'],
        ['Total Return', f"{total_return}%",
         'Excellent' if total_return > 50 else 'Good' if total_return > 20 else 'Moderate'],
        ['CAGR (Annual Return)', f"{backtest_data.get('cagr', 0)}%",
         'Strong' if backtest_data.get('cagr', 0) > 20 else 'Moderate'],
        ['Max Drawdown', f"{backtest_data.get('max_drawdown', 0)}%",
         'Low Risk' if backtest_data.get('max_drawdown', 0) < 10 else 'Moderate Risk'],
        ['Win Rate', f"{backtest_data.get('win_rate', 0)}%",
         'High' if backtest_data.get('win_rate', 0) > 60 else 'Moderate'],
        ['Total Trades', str(backtest_data.get('total_trades', 0)), 'Active Trading'],
        ['Buy & Hold Return', f"{buy_hold}%", 'Benchmark'],
        ['AI vs Buy & Hold', f"{outperformance:+}%",
         'AI Wins!' if outperformance > 0 else 'Buy & Hold Wins'],
    ]

    col_widths = [160, 120, 220]
    metrics_table = Table(metrics_data, colWidths=col_widths)
    metrics_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), DARK_GRAY),
        ('TEXTCOLOR', (0,0), (-1,0), WHITE),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 10),
        ('FONTNAME', (0,1), (0,-1), 'Helvetica'),
        ('FONTNAME', (1,1), (1,-1), 'Helvetica-Bold'),
        ('PADDING', (0,0), (-1,-1), 10),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#dddddd')),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [WHITE, LIGHT_GRAY]),
        ('TEXTCOLOR', (1,1), (1,1),
         PRIMARY if total_return > 0 else RED),
        ('TEXTCOLOR', (2,-1), (2,-1),
         PRIMARY if outperformance > 0 else RED),
        ('ALIGN', (1,0), (-1,-1), 'CENTER'),
    ]))
    story.append(metrics_table)
    story.append(Spacer(1, 20))

    story.append(Paragraph("AI Strategy Analysis", section_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#eeeeee'), spaceAfter=10))

    if total_return > buy_hold:
        analysis_text = f"""
        The TradeForge AI ensemble model (LSTM + XGBoost) successfully outperformed a simple
        buy-and-hold strategy on <b>{ticker}</b> by <b>{outperformance:+.2f}%</b>.
        The AI generated {backtest_data.get('total_trades', 0)} trades over the test period,
        achieving a win rate of {backtest_data.get('win_rate', 0)}% with a maximum drawdown
        of only {backtest_data.get('max_drawdown', 0)}%. The CAGR of {backtest_data.get('cagr', 0)}%
        indicates strong compounding performance over time.
        """
    else:
        analysis_text = f"""
        The TradeForge AI ensemble model (LSTM + XGBoost) generated {backtest_data.get('total_trades', 0)}
        trades on <b>{ticker}</b> over the test period. While the buy-and-hold strategy outperformed
        in this period, the AI strategy achieved a win rate of {backtest_data.get('win_rate', 0)}%
        with controlled drawdown of {backtest_data.get('max_drawdown', 0)}%.
        Consider retraining the model with more recent data for improved performance.
        """

    story.append(Paragraph(analysis_text.strip(), normal_style))
    story.append(Spacer(1, 20))

    story.append(Paragraph("Recent Trade Log", section_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#eeeeee'), spaceAfter=10))

    trades = backtest_data.get('trades', [])
    if trades:
        trade_header = ['Date', 'Action', 'Price (₹)', 'Shares', 'Profit/Loss (₹)']
        trade_data = [trade_header]

        for trade in trades[:15]:
            profit = trade.get('profit', None)
            profit_str = f"+{profit:,.2f}" if profit and profit > 0 else \
                        f"{profit:,.2f}" if profit and profit < 0 else "—"
            trade_data.append([
                trade.get('date', ''),
                trade.get('action', ''),
                f"{trade.get('price', 0):,.2f}",
                f"{trade.get('shares', 0):,}",
                profit_str
            ])

        trade_col_widths = [80, 60, 100, 80, 180]
        trade_table = Table(trade_data, colWidths=trade_col_widths)

        table_styles = [
            ('BACKGROUND', (0,0), (-1,0), DARK_GRAY),
            ('TEXTCOLOR', (0,0), (-1,0), WHITE),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,-1), 9),
            ('PADDING', (0,0), (-1,-1), 8),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#dddddd')),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [WHITE, LIGHT_GRAY]),
            ('ALIGN', (1,0), (-1,-1), 'CENTER'),
        ]

        for i, trade in enumerate(trades[:15], start=1):
            if trade.get('action') == 'BUY':
                table_styles.append(('TEXTCOLOR', (1,i), (1,i), PRIMARY))
            else:
                table_styles.append(('TEXTCOLOR', (1,i), (1,i), RED))
            profit = trade.get('profit', 0)
            if profit and profit > 0:
                table_styles.append(('TEXTCOLOR', (4,i), (4,i), PRIMARY))
            elif profit and profit < 0:
                table_styles.append(('TEXTCOLOR', (4,i), (4,i), RED))

        trade_table.setStyle(TableStyle(table_styles))
        story.append(trade_table)
    else:
        story.append(Paragraph("No trades were executed in this backtest period.", normal_style))

    story.append(Spacer(1, 30))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#eeeeee'), spaceAfter=10))

    disclaimer = """
    <b>Disclaimer:</b> This report is generated by TradeForge AI for educational and research purposes only.
    Past performance does not guarantee future results. This is not financial advice.
    Always consult a qualified financial advisor before making investment decisions.
    """
    disclaimer_style = ParagraphStyle(
        'Disclaimer', parent=styles['Normal'],
        fontSize=8, textColor=GRAY,
        spaceAfter=4, alignment=TA_LEFT
    )
    story.append(Paragraph(disclaimer.strip(), disclaimer_style))

    footer_style = ParagraphStyle(
        'Footer', parent=styles['Normal'],
        fontSize=8, textColor=PRIMARY,
        alignment=TA_RIGHT
    )
    story.append(Paragraph(f"Generated by TradeForge · {datetime.now().strftime('%Y-%m-%d %H:%M')}", footer_style))

    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()